# SLF4J Simple Logger configuration
org.slf4j.simpleLogger.defaultLogLevel=debug
org.slf4j.simpleLogger.showThreadName=true
org.slf4j.simpleLogger.showShortLogName=true
org.slf4j.simpleLogger.levelInBrackets=true

# File output (rec.log)
org.slf4j.simpleLogger.logFile=rec.log
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS
